### ISSUE TITLE
osc build --stage=c= and c+ is broken

### ISSUE THREAD

**Issue by brjsp** [openSUSE/obs-build#1016]
rpmbuild is incorrectly being called with --noprep instead of --short-circuit, which causes it to trash %_builddir and then go straight to executing %build on an empty source.

--stage=i= and i+ work correctly.

This seems to have been caused by commit e640c304248e6105a360e64d013190130fc3e890 (but i have not checked whether reverting it fixes the problem)

**Comment by brjsp** [comment]
(Pinging @mlschroe as the author of the offending commit)

**Comment by mlschroe** [comment]
Fixed. Thanks for the report!
