### ISSUE TITLE
Arch Linux builds are broken

### ISSUE THREAD

**Issue by pfactum** [openSUSE/obs-build#1027]
Hello.

Currently, Arch Linux builds are broken. For example, https://build.opensuse.org/package/show/home:post-factum/ridle

```
[   12s] processing recipe //.build-srcdir/PKGBUILD ...
[   12s] init_buildsystem --configdir /.build/configs --cachedir /var/cache/build //.build-srcdir/PKGBUILD build ...
[   12s] querying package ids...
[   12s] [1/134] installing hwdata-0.387-1
[   12s] Errors occurred, no packages were upgraded.
[   12s] exit ...
```

I *think* this may be triggered by the `pacman` upgrade to `7.0.0.r3.g7736133-1`.

Please check.

Thank you.

**Comment by adrianschroeter** [comment]
yes, issue got work arounded now
(pacman silently fails when download user is configured, but does not exist).

**Comment by agraef** [comment]
Thanks a bunch, guys, that was quick!

**Comment by ItachiSan** [comment]
Hey, how can one fix it locally with the build package?
