### ISSUE TITLE
Integration of debootstrap

### ISSUE THREAD

**Issue by leighman** [openSUSE/obs-build#111]
Hi,

Collabora's OBS currently uses a pretty ugly patch [1] to enable building deb packages with debootstrap.
It was done this way for two reasons:
1) We build a lot of debian packages and not all of them work outside the debootstrap setup (eg. if post-inst scripts have not been run)
2) We use arm boards as builders and these are not able to run hardware accelerated vms

We would like to try and upstream this work.

What would be your preferred approach for integrating debootstrap?
One suggested approach might be to use debootstrap's --foreign flag. This would mean that the prepared environment could still be run in a vm as other builds are. This would solve 1) but not 2).

Do you have any ideas on 2). Perhaps introducing a config flag that allows building outside a vm if the server is not public?

Any pointers on the new code layout since the refactor would be appreciated.

Thanks.

[1] http://cgit.collabora.com/git/singularity/tools/obs-build.git/commit/?id=2144acf8a0f82838e3ede5c57c74553a8cbef6c7

**Comment by mlschroe** [comment]
no feedback, so I assume it works. closing...
