### ISSUE TITLE
Install openSUSE-release package on buildroots by default

### ISSUE THREAD

**Issue by jobermayr** [openSUSE/obs-build#131]
Tools like pcsx2 or LLVM uses /etc/os-release or /etc/SuSE-release to check the distro at compile and/or runtime:
https://github.com/PCSX2/pcsx2/blob/master/cmake/Pcsx2Utils.cmake#L20
https://github.com/llvm-mirror/clang/blob/master/lib/Driver/ToolChains.cpp#L2849

To compile openSUSE specific code without the need to add "BuildRequires: openSUSE-release" manually both files should be present on all buildroots by default.

**Comment by mlschroe** [comment]
That's really a policy issue, the SUSE guys don't what to have a release package installed.

**Comment by adrianschroeter** [comment]
background to that is that binaries should not be product specific, because you never know which products will be made based on a maintained tree. Product specific things should be part of an extra package.
