### ISSUE TITLE
Please add tags for github to generate tarballs

### ISSUE THREAD

**Issue by xnox** [openSUSE/obs-build#133]
It seems that simply latest snapshot are dated and used in OBS to build packages.
Could you please tag the commits used for those builds? That way github would generate tarballs via it's "releases" feature and one would be able to just download the tarballs. I'm packaging obs-build for Debian and at the moment I have to rely on watching and downloading tarballs from: http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_14.04/build_(.*)\.orig\.tar\.gz which is ugly, because that tarball does not match the git checkout. Specifically sles11.conf is a symlink in git, yet it's a flat file in the orig.tar.gz OBS generated tarball.

Anyway... Please tag top-level commits such that one can download tarballs direct from github, without resorting to downloading tarballs by hash.

**Comment by abitrolly** [comment]
@xnox does https://github.com/openSUSE/obs-build/releases fix the issue?

**Comment by xnox** [comment]
YES!
