### ISSUE TITLE
"HTTP Error 400" occurs when "osc commit".

### ISSUE THREAD

**Issue by renzhengeek** [openSUSE/obs-build#161]
Hi,
When I want to commit my changs to server, "HTTP Error 400: Bad Request" occurs.

And I confirm that the usr & password are correct.

1. ~/.oscrc file
```
[general]
# URL to access API server, e.g. http://api.opensuse.org
# you also need a section [http://api.opensuse.org] with the credentials
apiurl = https://api.opensuse.org

*cut*

#http_headers = Host: foofoobar,
#       User: mumblegack
# Plain text password
#pass =
# Force using of keyring for this API
#keyring = 1

[https://api.opensuse.org]
user=omitted
pass=omitted
```

2.what I did:
``` 
n2:~/home:ZRen:branches:network:ha-clustering:Factory/ocfs2-test # osc commit 
Sending    _service
Deleting    add_cluster_options.patch
Deleting    allow_root_to_run.patch
Deleting    correct_install_path.patch
Deleting    library-for-aio-stress.patch
Deleting    mmaptruncate_hangup_clustersize_1048576.patch
Deleting    ocfs2-test-1.0.4+git.1382452089.8ec62e9.tar.bz2
Sending    ocfs2-test.spec
Deleting    remove_python_imports_timing.patch
Deleting    update-README-with-executing-instructions.patch
Sending    ocfs2-test-1.0.4+git.1425366927.4243065.tar.bz2
Transmitting file data .Server returned an error: HTTP Error 400: Bad Request
service validation error: Invalid attribute mode for element service
```

**Comment by adrianschroeter** [comment]
On Dienstag, 3. M�rz 2015, 01:15:57 wrote Eric Ren:
> Hi,
> When I want to commit my changs to server, "HTTP Error 400: Bad Request" occurs.
> 
> And I confirm that the usr & password are correct.
...
> Sending    _service
...
> Transmitting file data .Server returned an error: HTTP Error 400: Bad Request
> service validation error: Invalid attribute mode for element service

last line points to an invalid value in your _service file for "mode" attribute

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Jennifer Guild, Dilip Upmanyu, Graham Norton, HRB 21284 (AG N�rnberg) 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by adrianschroeter** [comment]
invalid

**Comment by renzhengeek** [comment]
Thanks a lot!
