### ISSUE TITLE
Broken filesystem on Archlinux since commit 7fb158b...

### ISSUE THREAD

**Issue by mmetak** [openSUSE/obs-build#164]
Commit:
https://github.com/openSUSE/obs-build/commit/7fb158b9d25a6806be943069f4805e8ff58b42f0

breaks filesystem installation on Archlinux.

**Comment by mlschroe** [comment]
Yes, the commit is bad. It should just delete the link. I patched the running system, so the builds should work again. I'll talk with Adrian tomorrow on how to do the real fix.

**Comment by adrianschroeter** [comment]
what is the error on ARCH ?

**Comment by adrianschroeter** [comment]
not sure if it is a good idea just to remove it, because other systems have created the directory already when  the dracut/systemd initrd decides to remove it.

In any case, it is a problem which should be solved in the initrd in first place from my POV. We can drop this workaround code then.

**Comment by adrianschroeter** [comment]
which package is creating /lock on Archlinux? IMHO it should be installed in preinstallation time, so the symlink would not be broken and the workaround would not run.

**Comment by mmetak** [comment]
what is the error on ARCH ?

[   36s] [9/104] installing filesystem-2015.02-1
[   36s] looking for conflicting packages...
[   36s] Packages (1) filesystem-2015.02-1
[   36s] error: failed to commit transaction (conflicting files)
[   36s] unable to --force directory-file conflicts
[   36s] filesystem: /var/lock exists in filesystem
[   36s] Errors occurred, no packages were upgraded.
[   36s] exit ...

**Comment by adrianschroeter** [comment]
btw, if someone would build a kernel-obs-build package pendant for Archlinux, we could also use the native Arch kernel and initrd. The host system one is only the fallback.

All what needs to be done is to have  the kernel and initrd packaged as

/.build.initrd.kvm
/.build.initrd.xen
/.build.kernel.kvm
/.build.kernel.xen

any takers for this job?

**Comment by mlschroe** [comment]
This is fixed with the commit mentioned above, right?
