### ISSUE TITLE
Add support for building Debian/Ubuntu packages with debbuild

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-build#173]
[debbuild](https://secure.deepnet.cx/trac/debbuild) is a tool written in Perl that accepts RPM spec files and outputs installable Debian packages as well as the equivalent of ".src.rpm" as ".sdeb" packages.

For those of us who would like to be able to build Debian packages using spec files, it would be fantastic if support was added to the Open Build Service to do just that.

**Comment by mlschroe** [comment]
Ok, there's now support for the 'debbuild' build engine. Enjoy!

**Comment by mlschroe** [comment]
Hey, I added a Debian:debbuild project to obs, which contains Debian_7.0 and Debian_8.0 repos. You can do your debbuild builds by just using those repos.

**Comment by Conan-Kudo** [comment]
@mlschroe Forgive me for sounding kind of ignorant, but how do I set a project to use debbuild instead of the normal Debian packaging build process?

**Comment by mlschroe** [comment]
If you setup a project you need to add repositories to build against, i.e. for Debian:8.0/standard. To use debbuild, you need to use Debian:debbuild/Debian_8.0.

E.g., use the following snippet for the project meta xml:
```
<repository name="Debian_8.0">
  <path project="Debian:debbuild" repository="Debian_8.0"/>
  <arch>x86_64</arch>
  <arch>i586</arch>
</repository>
```

Or use the advanced interface in the Add Repositories page of the build.opensuse.org UI.

**Comment by Conan-Kudo** [comment]
@mlschroe Neat. What about if I want to support it in a private instance. What do I need to do there?

**Comment by mlschroe** [comment]
How does your private instance look like? If you're using the interconnect to build.opensuse.org to have all the distributions, you'll also have the Debian:debbuild project available, probably at "openSUSE.org:Debian:debbuild". If you also have all the debian packages in some local project, you need to setup your own "Debian:debbuild" project, with the following project config:
```
Type: spec
BinaryType: deb
BuildEngine: debbuild
Support: debbuild pax
Keep: debbuild
```

**Comment by Conan-Kudo** [comment]
@mlschroe I have the interconnect enabled, but when I attempt to enter in "openSUSE.org:Debian:debbuild", it doesn't resolve to obtain a repoid.

**Comment by mlschroe** [comment]
Yeah, seems like you can't add remote repos with the Add Repositories page ;(

Ok, then select 'Advanced' from the project overview page, then select 'Meta' and add the xml snippet from above (using openSUSE.org:Debian:debbuild instead of Debian:debbuild, of course)

**Comment by Conan-Kudo** [comment]
@mlschroe I keep the existing snippet pointing to the normal Debian 7.0/8.0 repositories, too, right?

**Comment by mlschroe** [comment]
In that case you need to use a different name, as two repos can't have the same name.

E.g.:
```
<repository name="Debian_8.0">
  <path project="openSUSE.org:Debian:8.0" repository="standard"/>
  <arch>x86_64</arch>
  <arch>i586</arch>
</repository>
<repository name="Debian_8.0_debbuild">
  <path project="openSUSE.org:Debian:debbuild" repository="Debian_8.0"/>
  <arch>x86_64</arch>
  <arch>i586</arch>
</repository>
```

**Comment by Conan-Kudo** [comment]
@mlschroe It's not letting me save any changes to the meta XML at all.

**Comment by mlschroe** [comment]
Hmm, are you logged in and do you have write permissions for the project? You might also try osc instead, i.e. ```osc meta prj <yourprojectname> -e```

**Comment by Conan-Kudo** [comment]
@mlschroe I'm logged in as Admin at the moment, so I should have write permissions for everything, right?

**Comment by mlschroe** [comment]
Then maybe there's something wrong with the xml. Try osc, it should give you a better error message.

**Comment by Conan-Kudo** [comment]
@mlschroe Hmm, it turns out I can't add repos to subprojects that aren't up in the master project. I created a new master project and it worked there.

Also, my private OBS instance was set up using the [appliance installer ISO on the website](http://openbuildservice.org/download/), do I need to do anything to make debbuild stuff work, since the obs-build commit to add debbuild support came after I installed OBS?

**Comment by mlschroe** [comment]
Yes, you need versions with debbuild support for both obs-server and obs-build. I don't think the current appliance ISOs already contain those commits.

**Comment by mlschroe** [comment]
For now, you can try things out on build.opensuse.org... ;)

**Comment by Conan-Kudo** [comment]
@mlschroe I'm starting to use it on build.opensuse.org now. It's very nice. :)
