### ISSUE TITLE
rpm changed behaviour, spec file parse need to follow

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/obs-build#184]
We need to find a way to follow the changed behaviour of rpm when parsing complex conditions. For example:

%if ! 0%{?rhel} || 0%{?fedora}

has changed precedence. since quite some years, but our build script parser still handles it as

%if (! 0%{..}) || 0%{..}

not sure what we can take as trigger to follow this behaviour. If we just change the behaviour we will influence builds of current and older distros.

**Comment by mlschroe** [comment]
rpm did *not* change the behaviour. Did you smoke something bad?

**Comment by adrianschroeter** [comment]
Okay, then the build script parser was always wrong and not consistent with the one from rpm. Since it does not install certain buildrequires while rpm-build expects them to be installed.

can be verified by using

%if ! 0%{?rhel} || 0%{?fedora}
BuildRequires: something
%endif

and setting just %fedora to some value.

Do not use internet during vacation in bad mood ... stay away from it :)

**Comment by mlschroe** [comment]
I think you missed my point, your report was simply completely wrong. rpm parses ```%if ! 0%{?rhel} || 0%{?fedora}``` as ```%if (! 0%{?rhel}) || 0%{?fedora}```, it's our build script that (always) parsed it wrongly as ```%if ! (0%{?rhel} || 0%{?fedora})```.

Anyway, fixed in git. Next time, please try to get your claims a bit more correct.
