### ISSUE TITLE
When using debbuild engine, BuildRequires encapsulated in debbuild vendor tag aren't evaluated and installed

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-build#185]
As it says on the tin, when using the debbuild engine, BuildRequires aren't being evaluated and installed prior to attempting to build the package.

Here's my [package where I see the problem](https://build.opensuse.org/package/show/home:Pharaoh_Atem/lugaru), and the [build log from one of the builders](https://build.opensuse.org/package/live_build_log/home:Pharaoh_Atem/lugaru/Debian_7.0/x86_64).

Also, [here's the spec file](https://build.opensuse.org/package/view_file/home:Pharaoh_Atem/lugaru/lugaru.spec).

It appears the problem is that it's not evaluating the stuff inside the %if %{_vendor} == "debbuild" clauses to ensure the BuildRequires are properly evaluated. The BuildRequire for cmake, which is outside of the vendor clause, is installed prior to starting the build. But not the ones encapsulated in the conditional.

**Comment by Conan-Kudo** [comment]
It appears the problem is that it's not evaluating the stuff inside the %if %{_vendor} == "debbuild" clauses to ensure the BuildRequires are properly evaluated.

**Comment by Conan-Kudo** [comment]
I was able to prove that the vendor tag is the issue by branching my package and creating a derivative that flips the logic so that the information encapsulated by the debbuild vendor tag conditional was treated as the final "%else", leading it to be evaluated properly.

Thus, it builds!

Here's my [branched package](https://build.opensuse.org/package/show/home:Pharaoh_Atem:branches:home:Pharaoh_Atem/lugaru) and the [build log from one of the builders](https://build.opensuse.org/package/live_build_log/home:Pharaoh_Atem:branches:home:Pharaoh_Atem/lugaru/Debian_7.0/x86_64).

Also, [here's the spec file](https://build.opensuse.org/package/view_file/home:Pharaoh_Atem:branches:home:Pharaoh_Atem/lugaru/lugaru.spec).

I think this is proof enough that this is the issue.

**Comment by mlschroe** [comment]
I didn't know that the debbuild sets vendor/_vendor to debbuild.

The easiest way to do this is by adding a macro section to the project config that contains the buildengine definition. I just did that for Debian:debbuild in build.opensuse.org, the config now reads:

```
Type: spec
BinaryType: deb
BuildEngine: debbuild
Support: debbuild pax
Keep: debbuild

Macros:
%vendor debbuild
%_vendor debbuild
```

Does that solve your issue?

**Comment by Conan-Kudo** [comment]
Yes, it did.
