### ISSUE TITLE
Archlinux 'freetype2' still at pkgver=2.5.2???

### ISSUE THREAD

**Issue by mmetak** [openSUSE/obs-build#247]
Build log shows "installing freetype2-2.5.2-1" and causes some packages to fail to build.
How can this be?? It's from 2013-12-09!! Since then 'harfbuzz' dependency was introduced and because of that some packages failed to build.

**Comment by mlschroe** [comment]
I'm somewhat confused. Are you talking about build.opensuse.org? It contains freetype2 version 2.6.3-1. So if you're talking about OBS, what project are you referring to?

**Comment by mmetak** [comment]
Hi @mlschroe ,
must be something wrong with my project or something, don't know.
Example package in my project:
https://build.opensuse.org/package/live_build_log/home:metakcahura:e-git/elementary-git/Arch_Extra/x86_64
[125/192] installing freetype2-2.5.2-1

While in some other archlinux package it's the right version as you said.
https://build.opensuse.org/build/home:Generat0r/Arch_Extra/x86_64/palemoon/_log
[202/209] installing freetype2-2.6.3-1

**Comment by mlschroe** [comment]
Ok, it's some leftover from a previous build in your home:metakcahura project. It's used instead of the one from Arch:Extra because your home:metakcahura:e-git project builds against home:metakcahura.

So shall I delete all leftovers? Here's a list:

```
cegui-0.7.pkg.tar.xz
cegui.pkg.tar.xz
devil.pkg.tar.xz
dos2unix.pkg.tar.xz
ffmulticonverter-git.pkg.tar.xz
freeimage.pkg.tar.xz
freetype2.pkg.tar.xz
glfw.pkg.tar.xz
glm.pkg.tar.xz
gtk-engine-unico.pkg.tar.xz
irrlicht-docs.pkg.tar.xz
irrlicht.pkg.tar.xz
kmldonkey-svn.pkg.tar.xz
mldonkey-git.pkg.tar.xz
nvidia-cg-toolkit.pkg.tar.xz
ogre-1.8.pkg.tar.xz
ogre-docs.pkg.tar.xz
ogre.pkg.tar.xz
smc-data.pkg.tar.xz
```

**Comment by mmetak** [comment]
Please, do. Thanks.

**Comment by mlschroe** [comment]
Ok, done. There's quite a bit of rebuilding going on now. Please reopen if your problem still persists.
