### ISSUE TITLE
Failed to use --baselibs to build bi-arch package icecream-x86-arm

### ISSUE THREAD

**Issue by CapOM** [openSUSE/obs-build#261]
Hi,

It is possible to use the same original spec file to build bi-arch packages ? (bi-arch: https://en.opensuse.org/openSUSE:Build_Service_baselibs.conf)

I am trying to build the bi-arch package "icecream-x86-arm-0.9.7-1.armv7l.rpm" with the original spec file: https://review.tizen.org/git/?p=platform/upstream/icecream.git;a=blob;f=packaging/icecream.spec; and also just adding a baselibs.conf file which contains:

arch i686 targets armv7l:x86-arm i686:x86-arm aarch64:x86-arm
arch x86_64 targets armv7l:x86-arm x86_64:x86-arm aarch64:x86-arm

targettype x86-arm package icecream
targettype x86-arm autoreqprov off
targettype x86-arm extension -arm
targettype x86-arm requires "icecream" 
targettype x86-arm prefix /emul
targettype x86-arm +/

It succeeds to generates icecream-x86-arm-0.9.7-1.i686.rpm but it is not installable withing the gbs chroot because it claims it is not for arm.
I would expect to succeed since it is supposed to be a bi-arch package.

Any idea would be much appreciated.
Thx
Julien

**Comment by CapOM** [comment]
https://review.tizen.org/gerrit/#/c/67979/

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by CapOM** [comment]
Thx for pointing the mailing list and irc. (as for the patch I wrote a new one more appropriate https://review.tizen.org/gerrit/#/c/68353/ )
