### ISSUE TITLE
unhelpful error message "could not autodetect package type"

### ISSUE THREAD

**Issue by aspiers** [openSUSE/obs-build#271]
I did

```
osc bco home:darix:heroku-client/heroku-client
```

then added Leap via:

```
osc meta prj -e
```

then tried a build:

```
osc build openSUSE_Leap_42.1 x86_64
```

and the build failed with:

```
could not autodetect package type
```

I read the source code but that didn't help much as I'm a newbie to the OBS server code.  However after some head-scratching I got lucky and correctly guessed that it was because I had forgot to put any `<path>` in the project's `<repository name="openSUSE_Leap_42.1">`.  When I added:

```
<path project="openSUSE:Leap:42.1" repository="standard"/>
```

it all worked fine.  But @hennevogel suggested I should file a UX bug to make the error message more helpful in this case.

**Comment by adrianschroeter** [comment]
I fail to see the UX bug here, feel free to reopen when you have a concrete suggestion. (we could add a hint, but what to? Missing repos? Wrong prjconf? not supported packager name?....)
