### ISSUE TITLE
Package GPG signature check/sign (in ArchLinux... Elsewhere also...?)

### ISSUE THREAD

**Issue by ItachiSan** [openSUSE/obs-build#277]
At the moment, it is impossible to sign ArchLinux packages, even though there is native support through the ArchLinux build system (*makepkg*).

Maybe the package signing is an issue for also other package types (deb/rpm?).

In addition, GPG verification is broken inside the building machine, as there is no possibility to add to the internal keyring the GPG key (is the keyring installed in the base build image...?)

I will try to support you my best, even though I am not an Arch dev, just an AUR packager.

I would be glad to see this feature soon in OBS.

LINE TO BE REMOVED: I will adjust the title in order to be consistent with the situation :arrow_right: if package signing is present for Debian/RPM, I will say the problem is only on Arch

**Comment by mlschroe** [comment]
I think you're talking about OBS, not the build script, so my answer is about OBS.

OBS doesn't sign packages right after the build. To do the signing, the unencrypted private key would be needed on the build hosts, which is highly insecure.
Instead, packages get signed on a special secure signing server, so that the private keys never need to leave this host.

Arch Linux packages do get signed. Somehow the signatures don't end up in the generated repositories. The repository metadata itself is signed, which contains the sha256 checksum of the package files. Thus there should be no security issue.

I'll investigate what happens to the package signature files.

**Comment by mlschroe** [comment]
Ok, published signatures are back.

As for GPG key verification on the build hosts, we currently don't do that as all packages come from OBS anyway.

**Comment by ItachiSan** [comment]
@mlschroe so now built packages are signed with an OBS key? That would be great.

Also, in many cases I found myself downloading sources with a service file; checking that file with the proper .asc file and the correct key would be nice.
*makepkg* made it automatically, in this case maybe a service could do it?

**Comment by ItachiSan** [comment]
Ok, found that all packages and repo info are signed properely, which is really nice.
My only question is where is the public key available, so that people can add to the pacman keyring. :smile: 
Sorry to bother you @mlschroe ...!

**Comment by ItachiSan** [comment]
Seems there are some problems in package signing:
```
$ LANG=C yaourt -S telegram-desktop-light
resolving dependencies...
looking for conflicting packages...

Packages (1) telegram-desktop-light-0.9.56-1

Total Download Size:   16.16 MiB
Total Installed Size:  32.77 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 telegram-desktop-light-0.9.56-1-x86_64                            16.2 MiB  1931K/s 00:09 [-----------------------------------------------------] 100%
(1/1) checking keys in keyring                                                             [-----------------------------------------------------] 100%
error: telegram-desktop-light: unsupported signature format(0/1) checking package integrity                                                           [(1/1) checking package integrity                                                           [-----------------------------------------------------] 100%
error: GPGME error: No data
error: telegram-desktop-light: missing required signature
:: File /var/cache/pacman/pkg/telegram-desktop-light-0.9.56-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

**Comment by ItachiSan** [comment]
Ok, I understood where is the pubkey and I uploaded to a keyserver.
It was kinda unclear still. Mh.
