### ISSUE TITLE
What is difference among _TARGET_ARM_ , _M_ARM_ , and _ARM_?

### ISSUE THREAD

**Issue by leemgs** [openSUSE/obs-build#281]
I have continually been browsing the macros of the similar name for ARM CPU architecture from the CoreCLR source code. For example, There are three macros such as` _TARGET_ARM_` , `_M_ARM` , and `_ARM_` for ARM 32bit. Anyone who know the exact difference of these? Or where is documentation folder? Any comments will be helpful to us. Thanks in advance to them. :) 

* ARM 32bit 
1) `_TARGET_ARM_`  :  This macro is located in ./debug/, ./gcinfo/ , ./git/ , ./utilcode/ , ./vm/ , and ./zap/
2) `_M_ARM` :  This macro is located in ./pal/ , and ./inc/winrt/
3) `_ARM_` : This macro is located in ./gc , ./pal/ , and ./vm/ 

* ARM 64bit (e.g. AARCH64) 
1) `_TARGET_ARM64_`  : Not Yet Analyzed
2) `_M_ARM` : Not Yet Analyzed
3) `_ARM64_` : Not Yet Analyzed

\CC:  @jkotas, @benpye , @lemmaa, @seanshpark, @parjong, @sjsinju, @manu-silicon

**Comment by jkotas** [comment]
This was discussed in https://github.com/dotnet/corert/issues/440

**Comment by leemgs** [comment]
@jkotas  Thank you for sharing the related existing #440. 

To. Subscribers, Anyone who know the history of three arm macros? Can we unify the macros from three to one for convenient maintenance?

**Comment by jkotas** [comment]
We support cross-targeting of components like compilers or debuggers. The variant without the  `_TARGET_`  prefix is the host platform, the variant with  `_TARGET_`  prefix is the target platform, e.g.  `_X86_`  +  `_TARGET_ARM_ ` can be compiler running on x86 machine, producing ARM code. It means that both `_ARM_` and `_TARGET_ARM_` flavors are needed.

The one you can eliminate is `_M_ARM`. It is flavor predefined by Microsoft C++ compiler (https://msdn.microsoft.com/en-us/library/b0084kay.aspx). You should be able to replace it with just `_ARM_`.

**Comment by adrianschroeter** [comment]
this has nothing to do with obs-build.
