### ISSUE TITLE
debian packages that require essential packages to build may fail

### ISSUE THREAD

**Issue by hramrach** [openSUSE/obs-build#300]
I tried to build a Debian kernel. Looking through the changelogs I happened to spot a message about dropping build dependency in linux-libc-dev because it is essential package.

However, obs does not install linux-libc-dev and building a Debian kernel fails.

As a workaround you can add the dependency.

**Comment by bluca** [comment]
This would be fixed by: https://github.com/openSUSE/obs-build/pull/296

**Comment by hramrach** [comment]
ok, so this may be due to the blacklisting. Still if a package build-requires itself it should be installed before build. No way around that ;-)
