### ISSUE TITLE
Add whitespace between Accept/Decline buttons

### ISSUE THREAD

**Issue by jengelh** [openSUSE/obs-build#306]
It sometimes happens that we reviewers do not position our mice accurately enough and hit the wrong button in the review view (e.g. https://build.opensuse.org/request/show/440116 ).

Please consider adding some spacing between the "Approve" and "Disregard" buttons. 4em seems like a reasonable value; alternatively, right-aligning the Disregard button might also work.

Cc @DimStar77 
![rt](https://cloud.githubusercontent.com/assets/8861948/20262887/852e8a0c-aa64-11e6-84f6-d22cebeb403f.png)

**Comment by DimStar77** [comment]
How often did this already happen to you?

**Comment by jengelh** [comment]
Twice, though over many months. The third recorded instance actually hit cfarrell a few weeks ago, so I thought it's time to make a report :-)

**Comment by hennevogel** [comment]
Color might also help to convey this...

**Comment by hennevogel** [comment]
Please report this where it belongs -> https://github.com/openSUSE/open-build-service
