### ISSUE TITLE
build script broken when used with OBS and KVM

### ISSUE THREAD

**Issue by mmohring** [openSUSE/obs-build#333]
The current git master of the build script is broken when using it with OBS and KVM virtulization. Command line use with osc and chroot works.

**Comment by mmohring** [comment]
Last commit known to be working was b5c1826e701d0c5de5337660eab51f2227d8a060

**Comment by mmohring** [comment]
It causes the workers to reboot all the time until the retry limit is reached and then the build is marked as failed by OBS.

**Comment by adrianschroeter** [comment]
broken bash syntax from commit d135065c ... fixed

**Comment by mmohring** [comment]
You were faster. Works now 👍
