### ISSUE TITLE
[ArchLinux] Broken mesa deps

### ISSUE THREAD

**Issue by pfactum** [openSUSE/obs-build#346]
Due to recent changes in Arch Linux Mesa deps, some packages cannot be built in OBS failing with this error:

`conflict for provider of mesa needed by mesa-libgl, (provider mesa conflicts with installed mesa-libgl)`

I suspect this is the offensive line:

https://github.com/openSUSE/obs-build/blob/master/configs/arch.conf#L23

Instead, "mesa" should be preferred.

Also, "Prefer: mesa" in project config does not override this by default.

Adding "Ignore: mesa-libgl" kinda fixes this, but I'm not sure if this could break something else.

**Comment by pfactum** [comment]
Looks like a reasonable workaround:

`Prefer: -mesa-libgl libglvnd mesa`

**Comment by adrianschroeter** [comment]
this config is only used for standalone builds outside of OBS (and not using osc). 

Solved the issue in OBS for now, we will update the config the other day ....
