### ISSUE TITLE
Issue: Perl package unresolvable

### ISSUE THREAD

**Issue by triceratops1** [openSUSE/obs-build#349]
Log
`nothing provides perl<5.25 needed by perl-xml-libxml, nothing provides perl>=5.24 needed by perl-xml-libxml, nothing provides perl<5.25 needed by imagemagick, nothing provides perl>=5.24 needed by imagemagick`

my code
https://build.opensuse.org/package/show/home:meh924f:archlinux/cin#

**Comment by adrianschroeter** [comment]
this is a dependency issue in your setup and not a bug in build script. And this is neither a support forum.
