### ISSUE TITLE
Symlink to latest zsync is missing on the server, breaking AppImageUpdate

### ISSUE THREAD

**Issue by probonopd** [openSUSE/obs-build#358]
Using https://build.opensuse.org/package/binary/home:probono/Qactus?arch=x86_64&filename=Qactus-0-x86_64.AppImage&repository=AppImage

```
me@host:~$ '/home/me/Downloads/Qactus-0-x86_64.AppImage' --appimage-updateinformation
zsync|http://download.opensuse.org/repositories/home:/probono/AppImage/Qactus-latest-x86_64.AppImage.zsync
```

The URL looks correct but Qactus-__latest__-x86_64.AppImage.zsync is missing on the sever.
Hence under http://download.opensuse.org/repositories/home:/probono/AppImage/Qactus-latest-x86_64.AppImage.zsync I get __Error 404__.

This breaks AppImageUpdate.

Please create a symlink Qactus-__latest__-x86_64.AppImage.zsync.

**Comment by probonopd** [comment]
Not sure if this belongs into this project, so please forward if it doesn't.

**Comment by adrianschroeter** [comment]
works now
