### ISSUE TITLE
[Debian] fails to handle packages with control.tar.xz

### ISSUE THREAD

**Issue by suihkulokki** [openSUSE/obs-build#395]
Builds in debian unstable, using dpkg >= 1.19 will fail in the end with:

```
[  114s] r2-a19 finished "build hello_2.10-1+deb9u1.dsc" at Wed Oct 18 06:09:11 UTC 2017.
[  114s] 
hello-dbgsym_2.10-1+deb9u1_arm64.deb: has no hdrmd5
hello_2.10-1+deb9u1_arm64.deb: has no hdrmd5
```
Using perl to tun queryhdrmd5("hello_2.10-1_amd64.deb") results:
`hello_2.10-1_amd64.deb: control.tar.gz is not second ar entry
`
And ar x hello_2.10-1_amd64.deb results:
`control.tar.xz  data.tar.xz  debian-binary
`
Build/Deb.pm expects control.tar.gz, while .xz has been possible (but not used) until now. Looking at Deb.pm more closely, does it make sense to just use "dpkg-deb --ctrl-tarfile " instead of the manual parsing of deb file in perl code itself?

**Comment by mlschroe** [comment]
We can't expect dpkg to be installed, that's why dpkg-deb won't work.

**Comment by mlschroe** [comment]
(We'll also need to support this in libsolv to make building in OBS work)

**Comment by suihkulokki** [comment]
I noticed I need to fix build-pkg-deb in obs-build and osc has another place where control.tar.gz is directly referenced..

**Comment by mlschroe** [comment]
Also merged, thanks! Closing this issue.
