### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by evelikov** [openSUSE/obs-build#430]
Last release v2.5.0 is from 2014. I haven't tried using obs-build from git, but surely there are plenty of fixes and improvements done over the last ~4 years.

**Comment by alee-ccu** [comment]
I saw there is a new release message:
  https://github.com/openSUSE/obs-build/commit/215b4c344479b636723cdb5da89780856dca102a

It would be much more nice to have a tag for new releases.

**Comment by abitrolly** [comment]
There are new releases here https://github.com/openSUSE/obs-build/releases
