### ISSUE TITLE
obs-build complains of corrupt control.tar when installing debs for Ubuntu 18.04

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-build#436]
When doing builds for Ubuntu 18.04, `obs-build` complains about corrupt `control.tar` and `unxz` throws and error.

Sample errors:
```
[   47s] unxz: (stdin): File format not recognized
[   47s] unxz error: 256
[   47s] //.init_b_cache/rpms/autotools-dev.deb: corrupt control.tar file
[   47s] unxz: (stdin): File format not recognized
[   47s] unxz error: 256
[   47s] //.init_b_cache/rpms/binutils-common.deb: corrupt control.tar file
[   47s] unxz: (stdin): File format not recognized
[   47s] unxz error: 256
[   47s] //.init_b_cache/rpms/gcc-7-base.deb: corrupt control.tar file
[   47s] unxz: (stdin): File format not recognized
[   47s] unxz error: 256
[   47s] //.init_b_cache/rpms/gcc-8-base.deb: corrupt control.tar file
```

Full build log: [procdump_buildlog.txt](https://github.com/openSUSE/obs-build/files/1858505/procdump_buildlog.txt)

Reference build log: https://build.opensuse.org/package/live_build_log/home:Pharaoh_Atem:procdump/procdump/xUbuntu_18.04/x86_64

Reference package: https://build.opensuse.org/package/show/home:Pharaoh_Atem:procdump/procdump

**Comment by mlschroe** [comment]
Hmm. Perl bug. Worked around with commit c1698c9af6fc501016347ed6332171c17d0bd39a
