### ISSUE TITLE
Ubuntu 18.04 reports "nothing provides package" when built in private OBS instance

### ISSUE THREAD

**Issue by polmr** [openSUSE/obs-build#443]
I have configured an OBS private instance on an openSUSE Leap 42.3. Ubuntu 18.04 does not seem to recognize packages built with it when searching for dependencies. I've tried to reduce the problem to a minimum: 
In this scenario I have two packages: `father01` and `son01` within a project with repositories Ubuntu 16.04 & Ubuntu 18.04 configured. `son01` depends on `father01` (Build-Depends: `father01`, ...). `father01` builds ok for both repositories, but `son01` builds ok for 16.04 and fails for 18.04: it states "unresolvable" status -> `nothing provides father01`. I attach a zip with the contents of [both packages](https://github.com/openSUSE/obs-build/files/2027847/testPackages.zip)

**Comment by polmr** [comment]
Reported here too: https://github.com/openSUSE/open-build-service/issues/5059

**Comment by adrianschroeter** [comment]
please don't duplicate reports. use bugzilla.opensuse.org if you are not sure where it belongs.
