### ISSUE TITLE
Docker containers built with kiwi profiles don't get proper Provides

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/obs-build#449]
openSUSE:Factory:Containers/opensuse-tumbleweed image now builds two containers using _multibuild.
The docker flavor generates a proper docker image.

Issue here is that the tags are missing from the .containerinfo file, which makes it impossible to build against this container.

I'm not sure whether this is caused by the use of kiwi profiles or _multibuild or the combination.
I built a container with kiwi profiles but without _multibuild and it did not get a .containerinfo file at all: https://build.opensuse.org/package/binaries/home:favogt:branches:Virtualization:containers:images:openSUSE-Leap-15.0/opensuse-leap-image/containers

**Comment by darix** [comment]
Only 1 of your profiles is actually build. I would have expected an lxc and docker image at the end.

**Comment by Vogtinator** [comment]
> Only 1 of your profiles is actually build. I would have expected an lxc and docker image at the end.

It's a simplification to make the bug easier to reproduce. If you want the full picture, check https://build.opensuse.org/package/binaries/Virtualization:containers:images:openSUSE-Leap-15.0/opensuse-leap-image:docker/containers.

**Comment by darix** [comment]
The docker image has a containerinfo file. the lxc image does not. is that your issue?

**Comment by Vogtinator** [comment]
No.

> Issue here is that the tags are missing from the .containerinfo file, which makes it impossible to build against this container.

Open the file, see that there is no `"tags"` key.

**Comment by Vogtinator** [comment]
Fixed by https://github.com/openSUSE/obs-build/commit/1fd7c9f53bb340c311db458392ea795fa353b42c
