### ISSUE TITLE
[Debian] obs-build does pass arguments not possible

### ISSUE THREAD

**Issue by mckaygerhard** [openSUSE/obs-build#470]
when build a specific package for specific target (whatever target eitehr older or newer) some arguments are assumed, unless the version are supported or not, not always will be same for all Debian versiones the arguments beetwen releases, so please there's nay way to avoid unsuported arguments in the build service?

as example in this old case a "unsafe-io" are passed, that means the the container that builds the pacakge are not really the version that ships, by example if i forced lenny will faild, and i already know there's many services that still run older versions of debian, and i provide security patches for that versions:

```
[    9s] querying package ids...
[   10s] dpkg: unknown force/refuse option `unsafe-io'
[   10s] Type dpkg --help for help about installing and deinstalling packages [*];
[   10s] Use `dselect' or `aptitude' for user-friendly package management;
[   10s] Type dpkg -Dhelp for a list of dpkg debug flag values;
[   10s] Type dpkg --force-help for a list of forcing options;
[   10s] Type dpkg-deb --help for help about manipulating *.deb files;
[   10s] Type dpkg --license for copyright license and lack of warranty (GNU GPL) [*].
[   10s] Options marked [*] produce a lot of output - pipe it through `less' or `more' !
[   10s] exit ...
[   10s] 
[   10s] lamb15 failed "build sqliteman_1.2.2-1.1.dsc" at Thu Oct 11 02:14:12 UTC 2018.
```

**Comment by mlschroe** [comment]
unsafe-io was added by Sjoerd Simons <sjoerd.simons@collabora.co.uk> in commit 39456cc6f91538a4ad3cb328993b2b98c8d3757b:

```
    deb: Force unsafe io when install packages
    
    As the worker roots are transient there is little point in syncing
    everything to the filesystem, force dpkg to use unsafe-io.
    
    unsafe-io has been present in dpkg 1.15.8.6, which is older then the
    dpkg on any still supported debian or ubuntu release, so should be safe
    to do unconditionally
    
    Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
```

So what debian version are you building for?

**Comment by mckaygerhard** [comment]
hey! @mlschroe that cited demostrated that the process of build does not use the mandatory packages of the environment/debian dessired to building for! **that demostrated tha dpkg 1.15.8+ are used always! no matter what version of debian i building for!**

but i answered for you! i use the 5.0 version.. due i read and some sponsrs have containers available since etch.. in fact i need to build for etch also..

**Comment by mckaygerhard** [comment]
hey! @mlschroe that cited demostrated that the process of build does not use the mandatory packages of the environment/debian dessired to building for! **that demostrated that dpkg 1.15.8+ are used always! no matter what version of debian i building for! and does not honor the version of debian i wis to building for**

but i answered for you! i use the 5.0 version.. due i read and some sponsrs have containers available since etch.. in fact i need to build for etch also..

**Comment by mlschroe** [comment]
Fixed with commit 28463f3501d57438bd194b4ff3a7f51ed3d29ecc

**Comment by mckaygerhard** [comment]
hi @ mlschroe i see the commit 28463f3 and makes sense to me, i'll tested so then let me try with a lenny configuration and report feedback here! thanks so much for the good work!

**Comment by mckaygerhard** [comment]
hi @mlschroe i see the commit 28463f3 and makes sense to me, i'll tested so then let me try with a lenny configuration and report feedback here! thanks so much for the good work!

**Comment by mckaygerhard** [comment]
seems to work using vsftp from https://build.opensuse.org/package/show/home:mckaygerhard/vsftp thanks for all, now i must upload a lot of work..
