### ISSUE TITLE
Requires: /bin/fuser fails on CentOS 6

### ISSUE THREAD

**Issue by cfelder** [openSUSE/obs-build#472]
with the last package update the update of build on CentOS 6 fails at runtime with::
```
--> Processing Dependency: /bin/fuser for package: build-20180830-297.1.noarch
--> Finished Dependency Resolution
Error: Package: build-20180830-297.1.noarch (openSUSE_Tools)
           Requires: /bin/fuser
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

there is just a command ``/sbin/fuser`` provided in ``psmisc``

**Comment by mlschroe** [comment]
That may be true, but where is this /bin/fuser requirement coming from? I don't see anything like that in our spec file. Which spec file is used to build that build-20180830-297.1.noarch package?

**Comment by cfelder** [comment]
There has been some request on the OBS server which got merged, see link below:

https://build.opensuse.org/request/show/636385

**Comment by mlschroe** [comment]
Maybe, but that's an openSUSE packaging bug. The requires line is just in the spec file, not on git. And the specfile will be regenerated the next time an update is done.
So, I think that request should never have been accepted. I'll talk with the maintainer of the package.

**Comment by mlschroe** [comment]
The package has been fixed meanwhile.

**Comment by cfelder** [comment]
Alright. Thanks a lot.
