### ISSUE TITLE
Allow %rb_build_versions macro to expand to a macro itself

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-build#493]
I am currently packaging a ruby based application (vagrant), that has external plugins which be build from a single spec (in conjunction with vagrant). Since I only want to build vagrant with a single ruby version, I though that I'd define with which ruby version the plugins should be build. For example:
```
%vagrant_rb_build_versions ruby26
%vagrant_rb_build_abi ruby:2.6.0
```

My idea was, that a vagrant plugin would then put these two lines into its spec file:
```
%global rb_build_versions %vagrant_rb_build_versions
%global rb_build_abi %vagrant_rb_build_abi
```
and it would thereby be build with the correct ruby version.

The problem is that while rpm processes the file correctly, `obs-build` chokes on it and produces the following error message:
```
buildinfo is broken... it says:
unresolvable: nothing provides %{ruby%vagrant_rb_build_versions
      nothing provides STOP
      nothing provides }
```

My guess is that this comes from the configuration like this one: https://github.com/openSUSE/obs-build/blob/49931b232232881dee3e2592108d242a87c67ce9/configs/sle15.1.conf#L632 

Could the configuration be changed, so that `%rb_build_version` could itself expand to a macro?

If not, can maybe someone suggest a workaround?

**Comment by mlschroe** [comment]
This should work since the start of this year (commit 4c6d333472d1fae7e972509a6d7e93c125c13c90 to be exact)
