### ISSUE TITLE
obs-build RPM for SLES 12?

### ISSUE THREAD

**Issue by brianjmurrell** [openSUSE/obs-build#506]
I wonder if there is an already-packaged obs-build RPM for SLES 12[.3] available anywhere?

I see one on Fedora:

```
obs-build.noarch : A generic package build script
```

And I can surely roll my own, but I just wonder if anyone has done the work yet so that I can just get it from a repo.

**Comment by adrianschroeter** [comment]
On Dienstag, 18. Juni 2019, 22:07:57 CEST Brian J. Murrell wrote:
> I wonder if there is an already-packaged obs-build RPM for SLES 12[.3]
> available anywhere?

it is called just "build" there and part of the distribution (SDK).

Or a newer version is in the openSUSE:Tools project at your choice.

> 
> I see one on Fedora:
> 
> ```
> obs-build.noarch : A generic package build script
> ```
> 
> And I can surely roll my own, but I just wonder if anyone has done the work
> yet so that I can just get it from a repo.


-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de
