### ISSUE TITLE
build package requires python2 on leap 15.1

### ISSUE THREAD

**Issue by flaviodsr** [openSUSE/obs-build#509]
Installing the build (`20190604-lp151.315.1`) package on openSUSE Leap 15.1 requires also installing the `python-base` package.

I expect it to be requiring python3 instead as python2 will be EOL next year.

**Comment by DimStar77** [comment]
The only python script in this package is:

```/usr/lib/build/openstack-console: Python script, ASCII text executable```

**Comment by rsalevsky** [comment]
https://github.com/openSUSE/obs-build/blob/master/openstack-console looks like a simple python script so should be easy to get it to work with python3

**Comment by mlschroe** [comment]
IIRC it already works with python 3

Anyway, I removed the shebang line so everything should be fine. See commit e4809dbb4fdedac89c1e0b1f86bd02478e12007f
