### ISSUE TITLE
[  563s] /usr/lib/rpm/brp-suse.d/brp-15-strip-debug: line 33: /dev/fd/62: No such file or directory

### ISSUE THREAD

**Issue by brianjmurrell** [openSUSE/obs-build#513]
I have two identical build procedures for a package on Leap 15 and Leap 42.3.  Both are run inside of docker containers created with their own O/S version, built with the exact same recipe which basically installs _build_, adds the user that will be run in the container to the _sudoers_ file so that it can `sudo build ...` in the container.

However in the leap 42.3 container `sudo build ...` ends up failing with:

```
[  563s] calling /usr/lib/rpm/brp-suse.d/brp-05-permissions
[  563s] setting / to root:root 0755. (wrong owner/group abuild:abuild)
[  563s] setting /usr/ to root:root 0755. (wrong owner/group abuild:abuild)
[  563s] calling /usr/lib/rpm/brp-suse.d/brp-15-strip-debug
[  563s] /usr/lib/rpm/brp-suse.d/brp-15-strip-debug: line 33: /dev/fd/62: No such file or directory
[  563s] /usr/lib/rpm/brp-suse.d/brp-15-strip-debug: line 47: /dev/fd/62: No such file or directory
[  563s] error: Bad exit status from /var/tmp/rpm-tmp.gsXSMX (%install)
```

But the exact same process in the Leap 15.1 container doesn't run into this problem.  I have confirmed that `sudo` in the Leap 42.3 container does elevate the user to **root**.

Any ideas?

**Comment by brianjmurrell** [comment]
Ahhhh.  `/proc/` is empty in the Leap 42.3 chroot.

Is this a bug?

**Comment by brianjmurrell** [comment]
NVM.  I wasn't starting the container privileged.

**Comment by mlschroe** [comment]
FYI: commit b2e25c357d37dd4a8b9c2466b9408330c91be589 will make build print an error message if /proc could not be mounted.
