### ISSUE TITLE
Need ability to provide GPG keys to build chroot

### ISSUE THREAD

**Issue by brianjmurrell** [openSUSE/obs-build#518]
If I have a repo that I want to use in `build` but the GPG key for the packages in it are not in the default RPM keyring, I will get errors such as:

```
[2019-08-16T20:05:09.192Z] [   79s] [34/133] downloading https://download.opensuse.org/repositories/science:/HPC/openSUSE_Leap_42.3/x86_64/infinipath-psm-devel-3.3-36.1.x86_64.rpm ... 
[2019-08-16T20:05:10.558Z] [   80s] rpm verify failed
```

`build` needs a way to import GPG keys into the chroot so that packages like this can be verified.

**Comment by adrianschroeter** [comment]
The point is that a chroot build is insecure and you need to fully trust the downloaded rpms. Therefore your system gpg keys are used to verify.

You should not have this problem when doing a KVM build.

**Comment by brianjmurrell** [comment]
@adrianschroeter Just so I am clear then, I need to import the https://download.opensuse.org/repositories/science:/HPC/openSUSE_Leap_42.3 GPG key into the system keyring **before** running `build`?

**Comment by brianjmurrell** [comment]
So, yes, to close out my question, installing the key in the host environment was the solution.

Thanks!
