### ISSUE TITLE
add RHEL8 target

### ISSUE THREAD

**Issue by parf** [openSUSE/obs-build#521]
so far OBS only supports RHEL/CentOS6 and  RHEL7/CentOS targets

Please add support for RHEL8 (upcoming CentOS8)

**Comment by adrianschroeter** [comment]
On Montag, 16. September 2019, 21:13:41 CEST Sergey Parf wrote:
> so far OBS only supports RHEL/CentOS6 and  RHEL7/CentOS targets
> 
> Please add support for RHEL8 (upcoming CentOS8)

We have currently legal constraints with RHEL8, but we will add CentOS8
when it appears.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by bartmichu** [comment]
Is situation still the same now after recent changes around RHEL subscription plan?
