### ISSUE TITLE
Support for podman 1.6

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-build#529]
podman 1.6 defaults to systemd as the cgroup manager. in our build env we don't have a running systemd. (and I am kinda sure we dont want that either)

One way to get back the old behavior is calling ```podman build``` with ```--cgroup-manager=cgroupfs``` or inject a/patch the [libpod.conf][1]. My first approach was:

```podman-cgroups.patch 
Index: obs-build-20190923/call-podman
===================================================================
--- obs-build-20190923.orig/call-podman
+++ obs-build-20190923/call-podman
@@ -78,6 +78,6 @@ fi
 test -e "$BUILD_ROOT/proc/self" || mount -n -tproc none $BUILD_ROOT/proc
 
 # run the command
-exec chroot "$BUILD_ROOT" podman "$@"
+exec chroot "$BUILD_ROOT" podman --cgroup-manager=cgroupfs "$@"
``` 
 
But that is probably wrong as it will call podman all the time with the option. But if we want to use it as a buildenv tool (instead of docker/kvm/chroot) then it should actually use the normal cgroups manager. So we would need to patch the calls in build-recipe-docker.

Or would we prefer the 2nd option with patching the /etc/libpod.conf ?

[1]: https://github.com/containers/libpod/blob/master/docs/libpod.conf.5.md#options

**Comment by darix** [comment]
ok upstream we have this patch pending https://github.com/containers/libpod/pull/4228 which would revert to the old behavior.

Thank you to @vrothberg for all the valuable input on container stuff :)

**Comment by adrianschroeter** [comment]
libpod changed, so this should be obsolete
