### ISSUE TITLE
Some aarch64 systems only allow 32-bit in userspace, not in kernel, which breaks armv6/7 builds on such systems

### ISSUE THREAD

**Issue by ggardet** [openSUSE/obs-build#574]
Some aarch64 systems, such as the [N1SDP](https://en.opensuse.org/HCL:N1SDP) only allow to have 32-bit rootfs with a 64-bit (guest) kernel with KVM.

If I try `osc build openSUSE_Factory_ARM armv7l --vm-type=kvm` on a [N1SDP](https://en.opensuse.org/HCL:N1SDP), I get the following error because of the 32-bit guest kernel:
```
qemu-system-aarch64: can't apply global host-arm-cpu.aarch64=off: 'aarch64' feature cannot be disabled unless KVM is enabled and 32-bit EL1 is supported
```

So, `build-vm-kvm` should be updated to handle this case and use a 64-bit guest kernel, with a 32-bit roofs.

Here is how qemu test it: https://patchwork.ozlabs.org/project/qemu-devel/patch/20190816131719.28244-18-peter.maydell@linaro.org/

**Comment by adrianschroeter** [comment]
we are running this mode now in Factory
