### ISSUE TITLE
Flatpak target

### ISSUE THREAD

**Issue by KAMiKAZOW** [openSUSE/obs-build#588]
Flatpak support would be awesome. https://github.com/flatpak/flatpak-builder should be the tool to be interfaced with.

Flatpak Builder feature request: flatpak/flatpak-builder#112

This could potentially be something for Fedora's or openSUSE's GSoC projects.

**Comment by perlpunk** [comment]
I committed my changes. Now a single bundle file is built.

I also tried to build `org.telegram.desktop` but there was a build error.

**Comment by yellowhat** [comment]
Hi,
is there an example/guide to create a flatpak repository on obs?

Thanks

**Comment by perlpunk** [comment]
I forgot to update this issue.
I added experimental flatpak support in https://github.com/openSUSE/obs-build/pull/618, but more work is required.

**Comment by yellowhat** [comment]
@perlpunk thanks for the update, is there some sort of documentation on how to use flatpak on OBS?

Thanks

**Comment by perlpunk** [comment]
@yellowhat not yet.
An example project can be found here: https://build.opensuse.org/package/show/home:tinita:flatpak/org.gnome.Mahjongg
but it is not working (completely) yet

**Comment by yellowhat** [comment]
I have tried to rebuild it but I got:
```
error: LOCATION, FILENAME and NAME must be specified
```

**Comment by perlpunk** [comment]
@yellowhat yes, that's because YAML::XS is missing (and the missing error handling results in that unexpected error message).
That should be fixed by https://github.com/openSUSE/obs-build/pull/628

**Comment by yellowhat** [comment]
#628 has been merged. will it be present in the next tagged release?

Thanks

**Comment by perlpunk** [comment]
I remembered that I can add additional dependencies to the prjconf: https://build.opensuse.org/projects/home:tinita:flatpak/prjconf
As a workaround, I added perl-YAML-LibYAML there, and now the build succeeded.

**Comment by perlpunk** [comment]
> #628 has been merged. will it be present in the next tagged release?

That I don't know... @mlschroe @adrianschroeter maybe?

**Comment by yellowhat** [comment]
@perlpunk thank you very much for the information!!!

**Comment by adrianschroeter** [comment]
sure, it will be part of next release.

But it is also already deployed on build.opensuse.org in case you want to try ...

**Comment by perlpunk** [comment]
@adrianschroeter at least yesterday it complained about the missing YAML-LibYAML, so I added it in the prjconf.
Now the only thing missing seems to be the download of the package.
Currently
https://software.opensuse.org//download.html?project=home%3Atinita%3Aflatpak&package=org.gnome.Mahjongg
shows "no data".

**Comment by perlpunk** [comment]
I'm happy to announce that building works now, and there is basically only one addition that one has to make to the flatpak manifest:
put a `#!BuildVersion: 3.1.4` at the top of the YAML file to make sure the published files are versioned. that's necessary because flatpak manifests do not have a version field.

Here you can see the example app:
https://build.opensuse.org/package/show/home:tinita:flatpak/org.gnome.Mahjongg
You can now keep the original source urls, but for now you still have to put the tarballs into the OBS package.
We might add the possibility to let OBS download it before the build.

After the build and publish you can download the files under download.opensuse.org, e.g.:
https://download.opensuse.org/repositories/home:/tinita:/flatpak/flatpak/

**Comment by anthr76** [comment]
Hi @perlpunk I truly appreciate the contributions you made to make this happen! I'm trying to build my first flatpak though my builds are failing with

```
error: '/tmp/flatpakrepo' is not a valid repository
```
I'm chrooted into my build and /tmp is indeed empty. It looks as though it's failing on 

```
flatpak build-bundle --runtime-repo=https://dl.flathub.org/repo/flathub.flatpakrepo /tmp/flatpakrepo /usr/src/packages/OTHER/org.gnome-Mahjongg-3.36.flatpak org.gnome.Mahjongg 3.36
```

I'm trying to take a closer look though a bit stumbled at the moment.

**Comment by perlpunk** [comment]
@anthr76 if it's failing there, it's very probably that the build step didn't succeed. Can you look for prior error messages?
Did you branch the Template for this? https://build.opensuse.org/project/show/OBS:Flatpak:Templates

**Comment by anthr76** [comment]
Flatpak-builder indeed didn't pass

```
[  105s] + /.build/call-flatpak-builder --root /
[  105s] Unsharing environment
[  105s] + chroot / bash -c 'cd /usr/src/packages/FLATPAK_ROOT && flatpak-builder --default-branch=3.36.2 --force-clean --repo=/tmp/flatpakrepo build-dir /usr/src/packages/SOURCES/flatpak-local.yaml'
[  105s] error: No such metadata object a9488ee655b701658c0325fcdf0a891be42a84d39c92deef400cfbc30dafd022.commit
[  105s] Failed to init: Unable to find sdk org.gnome.Sdk version 3.36
```

I didn't branch the template at the time of creating as I didn't know it existed. Though I'm building almost verbatim off the example you provided. 

https://build.opensuse.org/package/show/home:anthr76:flatpak/org.gnome.Mahjongg I have what appears the correct meta. I'm going to take a closer look into `Failed to init: Unable to find sdk org.gnome.Sdk version 3.36`

**Comment by perlpunk** [comment]
The project config and meta are actually the most important ones, not only the one for the package.
That's why branching the template is the easiest way.
The documentation is already in a PR: https://github.com/openSUSE/obs-docu/pull/183
I will link to it when it has been merged, and I'll also write a blog post.

https://build.opensuse.org/projects/OBS:Flatpak:Templates/meta
https://build.opensuse.org/projects/OBS:Flatpak:Templates/prjconf

**Comment by anthr76** [comment]
Thanks for the quick help @perlpunk ! 

I do indeed have the SDKs present though failing for the source missing. I should be able to take it from here. 

```
GNOME Application Platform version 3.36                org.gnome.Platform                                                 3.36              system
GNOME Software Development Kit version 3.36            org.gnome.Sdk                                                      3.36              system
```

It was a bad assumption of me to expect it to work on TW :). Good day to you

**Comment by perlpunk** [comment]
It should also work for tumbleweed: https://build.opensuse.org/project/show/OBS:Flatpak

**Comment by perlpunk** [comment]
Hm, I added Tumbleweed to the Template project and also get a failure.
https://build.opensuse.org/package/show/OBS:Flatpak:Templates/FlatpakTemplate
It shows that the necessary tarball is extracted:
```
tar xf ../tars/org.gnome.Sdk-v3.36.x86_64.tar.gz
...
error: No such metadata object a9488ee655b701658c0325fcdf0a891be42a84d39c92deef400cfbc30dafd022.commit
Failed to init: Unable to find sdk org.gnome.Sdk version 3.36
```

**Comment by perlpunk** [comment]
I can't try with the latest tumbleweed locally because installing flatpak fails.
Here the output of `zypper in flatpak` in the latest tumbleweed docker container:
```
(51/75) Installing: system-user-flatpak-1.10.1-1.2.x86_64 ....................................................................................................................................................................................[error]
Installation of system-user-flatpak-1.10.1-1.2.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: ERROR: neither useradd nor busybox found!
error: %prein(system-user-flatpak-1.10.1-1.2.x86_64) scriptlet failed, exit status 1
error: system-user-flatpak-1.10.1-1.2.x86_64: install failed

Abort, retry, ignore? [a/r/i] (a): a
```

Will retry tomorrow and create a new issue.

**Comment by perlpunk** [comment]
Documentation is now live: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html#id-1.5.6.2.12
Here's a blog post: https://openbuildservice.org/2021/02/18/introducing-flatpak-builds/

**Comment by perlpunk** [comment]
I suggest to close this issue as the basic implementation is there.
For problems and features new issues should be created.

**Comment by adrianschroeter** [comment]
yep, great work Tina! :)

**Comment by perlpunk** [comment]
> yep, great work Tina! :)

Well, thanks to my colleagues for patiently answering questions and @mlschroe for implementing the chroot magic ;-)

**Comment by perlpunk** [comment]
@anthr76 it works now on Tumbleweed :)
https://build.opensuse.org/package/show/OBS:Flatpak:Templates/FlatpakTemplate
See also https://github.com/openSUSE/obs-build/issues/668
