### ISSUE TITLE
Memcached container fails to build

### ISSUE THREAD

**Issue by danidoni** [openSUSE/obs-build#598]
The memcached docker image fails to build as seen [here](https://build.opensuse.org/package/show/OBS:Server:Unstable:container:Leap151/memcached#build)

The error shown is

```[91m'-uninstall' is not a package name or capability.```

When trying the following command

```RUN zypper install -y memcachedRUN obs-docker-support --uninstall```

You can see the error in the [build log](https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable:container:Leap151/memcached/containers/x86_64)

**Comment by hennevogel** [comment]
@mlschroe  I guess this is dc4b6f25b2d7c41d16b539410f49aac78de8e40a
