### ISSUE TITLE
create_container_package_list only works if the container includes rpm

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/obs-build#609]
Various containers like opensuse/busybox and images derived from that don't have rpm inside (but the database).
For those, rpm from the host needs to be used to extract the package list. Currently it fails with

```
[   71s] [ INFO    ]: 07:44:20 | Bundle build results from /usr/src/packages/KIWI-docker
[   71s] [ INFO    ]: 07:44:20 | Creating kubic-coredns-image.x86_64-6.0.0-Build7.243.docker.tar.xz
[   71s] [ INFO    ]: 07:44:20 | --> Creating SHA 256 sum
[   71s] [ INFO    ]: 07:44:20 | Creating kubic-coredns-image.x86_64-6.0.0-Build7.243.packages
[   71s] [ INFO    ]: 07:44:20 | Creating kubic-coredns-image.x86_64-6.0.0-Build7.243.verified
[   74s] creating base package information
[   75s] chroot: failed to run command 'rpm': No such file or directory
[   75s] ... saving statistics
[   75s] ... saving built packages
[   75s] KIWI/kubic-coredns-image.x86_64-6.0.0-Build7.243.docker.containerinfo
```

**Comment by mlschroe** [comment]
Using the rpm from the host is pretty dangerous, it will create an empty db if it does not understand the db. So we need to copyout the database before accessing it.

But ok, I'll implement somthing like that.

**Comment by Vogtinator** [comment]
In this case it's actually fine, because those images were created with the rpm from the host in the first place.
(At least I don't think that it's possible to delete rpm with itself)

**Comment by mlschroe** [comment]
yes yes. Fixed in commit 0e2a29382b0f6cf53af4ed907f7b0f28dd3334cd

**Comment by mlschroe** [comment]
(completely untested, of course ;) )

**Comment by mlschroe** [comment]
Closing.

**Comment by Vogtinator** [comment]
Looks like it's working, `opensuse/busybox` has a full `.packages` file now. Thanks!
