### ISSUE TITLE
import handling in Build.pm non-effective in most cases

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-build#616]
Debugged this chain with Rudi:

we have tons of builds failing right now with missing perl digest modules. This is triggered by loading Helm.pm.
the import function in Build.pm has code that should only load the perl module for the current build job. so only if we have do_helm  we should load the helm code. In theory.... practically ... there is this line

```perl
$do_rpm = $do_deb = $do_kiwi = $do_arch = $do_collax = $do_livebuild = $do_snapcraft = $do_appimage = $do_docker = $do_fissile = $do_helm = 1 if !$do_rpm && !$do_deb && !$do_kiwi && !$do_arch && !$do_collax && !$do_livebuild && !$do_snapcraft && !$do_appimage && !$do_docker && !$do_fissile && !$do_helm;
```

so if no ```$do_*``` variable is set, lets just turn on all. But how can this happen? we have that nice for loop that checks what kind of build type we have and only sets this variable.

Well ... most code includes Build.pm with a simple

```perl
use Build;
```

instead of

```perl
use Build qw(:rpm);
```

That's why we run into the "do all" path. 

now the question is

1. do we fix all callers of Build.pm so the filtered loading works? Rudi tested that ```perl -I. -M"Build qw(:rpm)" -e "print 'hello\n';"``` also works. So it would be doable.
2. or we say we always want to load all modules, then we could simplify the module loading in Build.pm.

In any case we need to fix the prjconfs that are part of the build package and of course all the base distros in the OBS.

**Comment by adrianschroeter** [comment]
On Montag, 2. November 2020, 15:47:02 CET darix wrote:
> Debugged this chain with Rudi:
> 
> we have tons of builds failing right now with missing perl digest modules. This is triggered by loading Helm.pm.
> the import function in Build.pm has code that should only load the perl module for the current build job. so only if we have do_helm  we should load the helm code. In theory.... practically ... there is this line
> 
> ```perl
> $do_rpm = $do_deb = $do_kiwi = $do_arch = $do_collax = $do_livebuild = $do_snapcraft = $do_appimage = $do_docker = $do_fissile = $do_helm = 1 if !$do_rpm && !$do_deb && !$do_kiwi && !$do_arch && !$do_collax && !$do_livebuild && !$do_snapcraft && !$do_appimage && !$do_docker && !$do_fissile && !$do_helm;
> ```
> 
> so if no ```$do_*``` variable is set, lets just turn on all. But how can this happen? we have that nice for loop that checks what kind of build type we have and only sets this variable.
> 
> Well ... most code includes Build.pm with a simple
> 
> ```perl
> use Build;
> ```
> 
> instead of
> 
> ```perl
> use Build qw(:rpm);
> ```
> 
> That's why we run into the "do all" path. 
> 
> now the question is
> 
> 1. do we fix all callers of Build.pm so the filtered loading works? Rudi tested that ```perl -I. -M"Build qw(:rpm)" -e "print 'hello\n';"``` also works. So it would be doable.
> 2. or we say we always want to load all modules, then we could simplify the module loading in Build.pm.

we can not expect that all calling code gets adapted.

But the load of the module is meanwhile optional. Just failing if one really needs Helm chart handling.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by bugfinder** [comment]
well, at the moment the package build is failing if a package has build-time services active ...

**Comment by darix** [comment]
For me even a simple "osc build" against Debian:10 is failing:

```
security:keepassxc/keepassxc
cd security:keepassxc/keepassxc
osc build -x vim -k ../rpms/d10 -p ../rpms/d10 Debian_10 x86_64
```

**Comment by adrianschroeter** [comment]
On Montag, 2. November 2020, 17:04:23 CET darix wrote:
> For me even a simple "osc build" against Debian:10 is failing:
> 
> ```
> security:keepassxc/keepassxc
> cd security:keepassxc/keepassxc
> osc build -x vim -k ../rpms/d10 -p ../rpms/d10 Debian_10 x86_64
> ```

with current git master?

which error do you see?

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by darix** [comment]
Well lots of spam what the init_buildsystem part ... it works to build in the end but it should also not spam the log.

**Comment by adrianschroeter** [comment]
yes, the factory version is still broken, but git master got fixed yesterday.

**Comment by darix** [comment]
do we have an ETA for updates?
