### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/obs-build#621]
I am trying to replicate the build https://build.opensuse.org/package/live_build_log/home:andrew_z/bleachbit/xUbuntu_20.10/x86_64 locally on Fedora 33. I discovered that `debian/` files for this project are OBS specific and documented at the page below.

https://en.opensuse.org/openSUSE:Build_Service_Debian_builds

However, the page lacks information about how to convert and run the build locally.

**Comment by abitrolly** [comment]
When I try `build` command from `obs-build` package, I get this.
```
❯ cd debian/
❯ build
logging output to /var/tmp/build-root/.build.log...
[    0s] Memory limit set to 10565290KB
[    0s] Using BUILD_ROOT=/var/tmp/build-root
[    0s] Using BUILD_ARCH=x86_64:i686:i586:i486:i386
[    0s] 
[    0s] 
[    0s] blackred started "build bleachbit.dsc" at Wed Nov 11 06:44:43 UTC 2020.
[    0s] 
[    0s] 
[    0s] processing recipe /home/abiroot/p/bleachbit/debian/bleachbit.dsc ...
[    0s] init_buildsystem --configdir /usr/lib/build/configs --cachedir /var/cache/build --repository zypp:// /home/abiroot/p/bleachbit/debian/bleachbit.dsc ...
[    0s] expanding package dependencies...
[    0s] Warning: distribution not specified, assuming 'default' (see /usr/lib/build/configs).
[    0s] expansion error
[    0s]   nothing provides debhelper >= 4
[    0s]   nothing provides python3
[    0s]   nothing provides gettext
[    0s]   nothing provides desktop-file-utils
[    0s] 
[    0s] blackred failed "build bleachbit.dsc" at Wed Nov 11 06:44:43 UTC 2020.
[    0s] 
```

**Comment by abitrolly** [comment]
`osc build` didn't work either.
```
❯ osc build
Error: '/home/abiroot/p/bleachbit' is not an osc project dir or working copy
Current directory looks like git.
```

**Comment by adrianschroeter** [comment]
you need to specify the location of the distro repository and you need to select the right distro config on command line.

**Comment by abitrolly** [comment]
@adrianschroeter thanks for the clarification. Do you mean native package repository for the distro? I am not yet sure how it looks like for Ubuntu. Why this location is not in the distro config?

**Comment by abitrolly** [comment]
After just a few weeks I found the right command.
```
$ osc build --vm-type=kvm xUbuntu_20.10
```
Here `xUbuntu_20.10` a custom name for repository from upstream OBS project and `--vm-type=kvm` is needed to make the build more secure.
