### ISSUE TITLE
debtransform: produces broken builds for Ubuntu 20.10

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/obs-build#633]
`debtransform` converts native packages to **non-native** by creating `.orig.tar.gz` file.

```
[  101s] Found files matching debian.*, running debian transformer...
[  101s] release: (4.1), release (DEB) (4.1)
[  101s] ** Started: debtransform --release 4.1 //usr/src/packages/SOURCES //usr/src/packages/SOURCES/bleachbit.dsc //usr/src/packages/SOURCES.DEB
[  101s] No DEBTRANSFORM-TAR line in the .dsc file.
[  101s] Attempting automatic discovery of a suitable source archive.
[  101s] Source archive chosen for transformation: bleachbit-4.1.1.tar.gz
[  101s] No DEBTRANSFORM-FILES-TAR line in the .dsc file.
[  101s] Attempting automatic discovery of a debian archive.
[  101s] Hardlinking //usr/src/packages/SOURCES/bleachbit-4.1.1.tar.gz to //usr/src/packages/SOURCES.DEB/bleachbit_4.1.1.orig.tar.gz
[  101s] files d7dd9b320579971308c78245c0a3ff2f 1147196 bleachbit_4.1.1.orig.tar.gz
[  101s] Scanning //usr/src/packages/SOURCES.DEB/bleachbit_4.1.1.orig.tar.gz...
[  101s] Generating //usr/src/packages/SOURCES.DEB/bleachbit_4.1.1.diff
[  101s] Processing file "//usr/src/packages/SOURCES/debian.rules"...
[  101s] Processing file "//usr/src/packages/SOURCES/debian.control"...
[  101s] Processing file "//usr/src/packages/SOURCES/debian.changelog"...
[  101s] Writing //usr/src/packages/SOURCES.DEB/bleachbit_4.1.1.dsc
```

This makes package version invalid, because non-native packages should have a suffix. Newer versions of `dpkg-source` make this an error.
```
[  103s] dpkg-source: error: non-native package version does not contain a revision
```

`debtransform` should either append suffix automatically, or don't convert the package from native.

**Comment by abitrolly** [comment]
Here is the proof for `openSUSE:Tools/build` https://build.opensuse.org/package/rdiff/openSUSE:Tools/build?linkrev=base&rev=427

**Comment by noscript** [comment]
This completely block the builds for Ubuntu 20.10. Any workaround how to append `-1` revision suffix?

**Comment by abitrolly** [comment]
@noscript yep, submitting a PR right now.

**Comment by noscript** [comment]
@abitrolly thanks!

Until this lands to build.opensuse.org I came up with this. I can use `<service name="set_version"/>` to to read the version number from `.obsinfo` file, which can be generated externally with e.g. GitHub Actions and then downloaded with `<service name="download_url">`.

**Comment by abitrolly** [comment]
@noscript it should be enough to add `-1` Debian revision to your .dsc manually. This is what `openSUSE:Tools/build` project did.

**Comment by noscript** [comment]
My version number is generated dynamically by `tar_scm`:
```xml
  <service name="tar_scm">
    <param name="scm">git</param>
   ...
    <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>
  </service>
```

But I cannot appernd `-1` to `versionformat`, dashes get removed.

**Comment by abitrolly** [comment]
@noscript that might be another issue. Do you see `debtransform` references in your build log?

**Comment by noscript** [comment]
I use `debtransform` to update version in `ChangeLog` and `.dcs`:
```
[  152s] dpkg-buildpackage: info: source changed by debtransform <build@opensuse.org>
...
[  153s] dpkg-source: error: non-native package version does not contain a revision
```

**Comment by noscript** [comment]
Using `.obisinfo` file was too good solution to be true. Adding `-1` revision now broke `rpmbuild`:
```
[ 400s] error: line 5: Illegal char '-' (0x2d) in: Version: 0.8.2.pre106-1
```

So it is not possible to build rpm and deb packages in the same project, sigh :disappointed:

**Comment by abitrolly** [comment]
I sent several letter to various mailing lists and they didn't pass, first because I was not a member, then because the lists migrated to different address, then there were some problems with archives and I couldn't see them, and I've exhausted my try attempts.

You can may try send a mail yourself pointing to this issue and the solution in https://github.com/openSUSE/obs-build/pull/646 and maybe it will be integrated.

**Comment by adrianschroeter** [comment]
On Dienstag, 5. Januar 2021, 23:54:53 CET Sergey Vlasov wrote:
> Using `.obsinfo` file was too good solution to be true. Adding `-1` revision now broke `rpmbuild`:
> ```
> [ 400s] error: line 5: Illegal char '-' (0x2d) in: Version: 0.8.2.pre106-1
> ```
> 
> So it is not possible to build rpm and deb packages in the same project, sigh :disappointed: 

not in the same repository to be exact (but you can do so in same project of course).


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by nickbroon** [comment]
Could this be the cause of https://github.com/openSUSE/osc/issues/888 ?

**Comment by abitrolly** [comment]
Yes, it is.
