### ISSUE TITLE
Flatpak build on tumbleweed doesn't work

### ISSUE THREAD

**Issue by perlpunk** [openSUSE/obs-build#668]
The output of `flatpak list` is empty, and flatpak-builder doesn't find the installed images either:
```
tar xf ../tars/org.gnome.Sdk-v3.36.x86_64.tar.gz
...
error: No such metadata object a9488ee655b701658c0325fcdf0a891be42a84d39c92deef400cfbc30dafd022.commit
Failed to init: Unable to find sdk org.gnome.Sdk version 3.36
```
https://build.opensuse.org/package/show/OBS:Flatpak:Templates/FlatpakTemplate

(Mentioned in #588 )

**Comment by perlpunk** [comment]
I tested with org.freedesktop.Platform.openh264

* install that via flatpak/flathub in tumbleweed container
* create tarball
* run fresh tumbleweed container and unpack tarball
--> flatpak list shows it


If I do this with the current tarball (https://build.opensuse.org/project/show/OBS:Flatpak), flatpak list doesn't show anything.

Luckily unpacking the tarball from tumbleweed on Leap 15.2 also works. So the packages under OBS:Flatpak need to be generated on tumbleweed now.

**Comment by adrianschroeter** [comment]
I am not 100% sure why this is an issue here, is this a problem of the build script? are you going to work on it?

OBS:Flatpak is building also again Tumbleweed (but this is not a build script topic).

**Comment by perlpunk** [comment]
I'm not sure where to put this issue. I am working on it, but I can't set myself as an assignee.

The rpms in OBS:Flatpak need to be fixed and built on tumbleweed instead of leap. I'm still figuring out what the difference is.

**Comment by adrianschroeter** [comment]
hm, no idea why setting yourself as assignee is not work for you... but here you have it :)

**Comment by perlpunk** [comment]
I created several base images with a Tumbleweed container and put them here:
https://build.opensuse.org/project/show/home:tinita:branches:OBS:Flatpak

Then I created a project and set the repository path to `home:tinita:branches:OBS:Flatpak`

The app is now building fine on Leap *and* Tumbleweed, and I can install all 3 generated .flatpak bundles on my Leap 15.2.

I'll now create the rest of the base images and put them into https://build.opensuse.org/project/show/OBS:Flatpak

I'll update the code in https://github.com/openSUSE/flatpak-base-to-rpm to use Tumbleweed as the base container.

**Comment by perlpunk** [comment]
Working on Tumbleweed now: https://build.opensuse.org/package/show/OBS:Flatpak:Templates/FlatpakTemplate
In the future issues related to that shuol be opened in https://github.com/openSUSE/flatpak-base-to-rpm
