### ISSUE TITLE
Arch Linux packages are stuck in "excluded" state

### ISSUE THREAD

**Issue by pfactum** [openSUSE/obs-build#677]
Since very recently, newly updated/bumped Arch Linux packages are stuck in the "excluded" state.

Examples:

* https://build.opensuse.org/package/show/home:post-factum/mergerfs
* https://build.opensuse.org/package/show/home:post-factum:kernels/linux-pf-next

I've tried triggering `rebuild` and `restartbuild` with no luck. Also it seems due to this issues the packages are removed from the generated repos.

Please help.

Thanks.

**Comment by adrianschroeter** [comment]
It is unlikely that this is a build script code bug. please come to our mailing list or irc channel for support.
