### ISSUE TITLE
pbuild cannot fetch the project _meta from OBS

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-build#684]
I wanted to give the new pbuild tool a try to build a few packages against a project on OBS. Unfortunately, I cannot get it to work, as pbuild appears to just directly fetch the project's `_meta` and I haven't found an option to pass it any credentials:
```ShellSession
$ ./pbuild --obs https://api.opensuse.org --dist obs:/home:fcrozat:matryoshka/standard .
download of https://api.opensuse.org/source/home:fcrozat:matryoshka/_meta failed: 401 Unauthorized
```

`osc api source/home:fcrozat:matryoshka/_meta` on the other hand works.

**Comment by mlschroe** [comment]
You need to use the interconnect url, i.e. `https://api.opensuse.org/public`

**Comment by dcermak** [comment]
Michael Schroeder ***@***.***> writes:

> You need to use the interconnect url, i.e. `https://api.opensuse.org/public`

Ah, that makes sense, thanks!

Should this be documented? After all that would make it pretty obvious
how to bypass OBS' authentication mechanism.

**Comment by coolo** [comment]
That's the same route you add as remoteurl for interconnected instances

**Comment by coolo** [comment]
https://openbuildservice.org/files/manuals/obs-admin-guide.pdf - chapter 4.2.1

**Comment by adrianschroeter** [comment]
you guys are about to create the need to close this route :/

Please use public mirrors instead, we will not be able to feed the world with our single production instance.

**Comment by coolo** [comment]
What is a public mirror for home:fcrozat:matryoshka/_meta ?

**Comment by adrianschroeter** [comment]
On Freitag, 23. April 2021, 08:23:30 CEST Stephan Kulow wrote:
> What is a public mirror for home:fcrozat:matryoshka/_meta ?

you do not need _meta to build against the repo. Just use 
the --repo $url.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dcermak** [comment]
Adrian Schröter ***@***.***> writes:

> On Freitag, 23. April 2021, 08:23:30 CEST Stephan Kulow wrote:
>> What is a public mirror for home:fcrozat:matryoshka/_meta ?
>
> you do not need _meta to build against the repo. Just use 
> the --repo $url.

The catch here is that home:fcrozat:matryoshka contains SLES
repositories, which are not published. So unless matryoshka republishes
all of SLES, that will not work, right?
