### ISSUE TITLE
build script produces _ccache.tar for no reason

### ISSUE THREAD

**Issue by lnussel** [openSUSE/obs-build#702]
The build script always produces a _ccache.tar when ccache is enabled. The file is really big for eg kernel builds and not used in local builds. It's only relevant to the obs worker. So would make sense to generate it only when needed. Ie the obs worker has to communicate that somehow.

**Comment by mlschroe** [comment]
This as been fixed a could of weeks ago: it now only creates the _ccache.tar file if the --ccache-create-archive option is used.
