### ISSUE TITLE
[pbuild] Confusing "have choice for" error while doing a cross build for aarch64

### ISSUE THREAD

**Issue by ismail** [openSUSE/obs-build#706]
I'm trying to cross-build a project on an x86-64 machine. The project has only aarch64 as target on OBS:

```
~/src/obs-build/pbuild --dist=$DIST --vm-type=qemu --arch=aarch64 --repo $REPOURL
```

Note: $DIST.conf is just extracted from `osc meta prjconf ...` 

This results in a cascade of errors, similar to:

```
have choice for libreadline.so.7()(64bit) needed by bc: libreadline7 libreadline7-64bit
```

The problem is that libreadline7 rpm is in $REPOURL/aarch64 and libreadline7-64bit is under $REPOURL/aarch64_ilp32, so there should be no choice error (I think). Needless to say, this works on OBS without a problem.

**Comment by mlschroe** [comment]
Well the package names are different, so both packages are available and you get the choice errors. That's not really a bug. It only works in OBS because the "useforbuild" repos do not have both packages available.

The default architecture filter for aarch64 is `aarch64,aarch64_ilp32,armv8l`. You can specify a custom arch filter with the repo url like this:
```
--repo rpm-md+archfilter=aarch64
```

**Comment by ismail** [comment]
This fixes the "have choice for" error, thank you!

**Comment by ismail** [comment]
@mls Is there a way to do this configuration on the server side? As armv8l and aarch64_ilp32 are generally irrelevant for mainstream.

**Comment by mlschroe** [comment]
What server? Your OBS server? If you do not want those rpms, why do you publish them?

**Comment by ismail** [comment]
> What server? Your OBS server? 

Well, yes, but also applies to any OBS installation.

> If you do not want those rpms, why do you publish them?

Because I don't see a way to disable publishing them, I tried:

```ExportFilter: -64bit-.*\.aarch64_ilp32\.rpm$```

But that didn't prevent publishing of these. If you have a suggestion to disable aarch64_ilp32 support, I'm all ears :-)

**Comment by mlschroe** [comment]
Don't use an ExportFilter, but a PublishFilter!

**Comment by mlschroe** [comment]
```
PublishFilter: 64bit-.*\.aarch64_ilp32\.rpm$
```

**Comment by ismail** [comment]
> ```
> PublishFilter: -64bit-.*\.aarch64_ilp32\.rpm$
> ```

This is what I get for stealing from openSUSE:Factory, works like a charm, thank you!
