### ISSUE TITLE
createdebdeps fails to find some packages

### ISSUE THREAD

**Issue by JKingweb** [openSUSE/obs-build#707]
I'm trying to build a Debian package from a `dsc`; its only build dependency is `debhelper`. The following command:

```
sudo build --clean --dist debian --repo 'http://deb.debian.org/debian/?dist=buster&component=main&component=contrib&component=non-free'
```

Results in the following relevant output:

```
[    0s] /usr/lib/build/createdebdeps --cachedir=/var/cache/build --archpath x86_64:i686:i586:i486:i386 http://deb.debian.org/debian/?dist=buster&component=main&component=contrib&component=non-free
[    4s] expanding package dependencies...
[    6s] expansion error
[    6s]   nothing provides libreadline4
[    6s]   nothing provides cracklib2
[    6s]   nothing provides diff
[    6s]   nothing provides module-init-tools
[    6s]   nothing provides sysvinit
```

Am I doing something wrong?

**Comment by mlschroe** [comment]
No, it's the build tool that's to blame. The shipped debian configuration file is way too old. I now uploaded configs for debian7 - debian11 and removed the unversioned outdated one. So with buster you would need to use `--dist debian10`.

**Comment by JKingweb** [comment]
Thank you, Michael! Works like a charm now, at least with the `debian10` configuration. I also tried `debian11`, which didn't work, but that may be expected as I received different errors in two attempts an hour apart; perhaps the mirror I'm using is partially outdated.

You may want to also remove the unversioned (and presumably similarly outdated) `debian-unstable` and `ubuntu` configurations, by the way.
