### ISSUE TITLE
QEMU VM build uses wrong VM_ROOTDEV and VM_SWAPDEV

### ISSUE THREAD

**Issue by linnaea** [openSUSE/obs-build#715]
https://github.com/openSUSE/obs-build/blob/a66826e168f0efc63d207bb8b21f3a8e6f29ff23/build-vm-qemu#L37-L46

`vm_verify_options_qemu` is called before `vm_startup_qemu`, and thus `qemu_device` would not be set here, causing any architecture using virtio blockdev to get an incorrect `VM_ROOTDEV` and `VM_SWAPDEV`.

**Comment by adrianschroeter** [comment]
right, moved it to a better place now.
