### ISSUE TITLE
obs build default user is abuild, build process will access root permission file, how to solve it?

### ISSUE THREAD

**Issue by system-thoughts** [openSUSE/obs-build#732]
Hi, this question is for help.
obs build default user is abuild, build process will access root permission file, so access will fail, how to solve it?

**Comment by mlschroe** [comment]
Most builds can (and should!) be changed to make non-root builds work. If a build absolutley needs to be done as root, you can put a
```
#needsrootforbuild
```
marker in the recipe file.
