### ISSUE TITLE
Dockerfile parsing fails with "from <image> as <alias>" lines - treats <alias> as image name

### ISSUE THREAD

**Issue by kkaempf** [openSUSE/obs-build#751]
# Issue Description

A `Dockerfile` with

```
FROM opensuse/leap:15.3 as base
...
FROM base AS build
...
```

fails to build with

```
unresolvable: nothing provides container:base:latest
```

Expected Result
============

The dependency parse recognizes the alias declaration and can handle it correctly.

How to Reproduce
===============

Use any Dockerfile with an alias declaration.

Further Information
===============

n/a

**Comment by adrianschroeter** [comment]
https://github.com/openSUSE/obs-build/pull/754 is supposed to fix it

**Comment by adrianschroeter** [comment]
merged, should be deployed thursday morning latest.
