### ISSUE TITLE
Config has written to use shadow but build still ask whether use busybox

### ISSUE THREAD

**Issue by zyppe** [openSUSE/obs-build#810]
![2022-04-13 101325](https://user-images.githubusercontent.com/10075036/163086113-54874f75-4309-436d-aef7-761872719310.png)
As showed in the picture, I use 15.4's config to build, it ask me whether to use busybox for useradd.
And if I write "-X shadow" to force to use shadow, it will just break down my build environment!
Please help to resolve.
My build is from Tools repo.

**Comment by 210hcl** [comment]
`error: failed to exec scriptlet interpreter /bin/sh: No such file or directory`
This error often display in build.
