### ISSUE TITLE
[Arch Linux] Builds are blocked with "downloading 3 dod packages" message

### ISSUE THREAD

**Issue by pfactum** [openSUSE/obs-build#824]
Since recently Arch Linux packages cannot be built. They are stuck in the "blocked" state with the "downloading 3 dod packages" message.

Example: https://build.opensuse.org/package/show/home:post-factum/litter

Not sure what that means, what changed and where, and how to fix that.

Please help.

Thanks.

P.S. Before opening the issue here I tried reporting it in the IRC channel, but got no response.

**Comment by avallach2000** [comment]
I faced the same issue and found that there was a similar problem with CentOS 7 a couple of years ago: https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/NPAHJCTVAWKAIVZNL2KLIG7X7SBYXLNU/

It seems that something is wrong with the certain packages in OBS Arch repos, but I don't know how to investigate it. For now we cannot build or rebuild any Arch package. And everything we got is this message:

> This package waits for other packages to be built. These can be in the same or other projects.
> No build possible at the moment, waiting for jobs in other repositories
> blocked: downloading 3 dod packages

Note that number of dod packages vary from one package to another. If your package depends, for example, on some Qt stuff you’ll got 6 dod packages, but there’s no way to find out what is actually wrong.

List of blocked packages (pfactum’s + mine):
* https://build.opensuse.org/project/monitor/home:post-factum?arch_x86_64=1&blocked=1&defaults=0&repo_Arch=1
* https://build.opensuse.org/project/monitor/home:avallac_h:lemu-archlinux?arch_x86_64=1&blocked=1&defaults=0&repo_Arch=1

Just an assumption: according to https://build.opensuse.org/repositories/Arch:Core/ OBS uses http://ftp.hosteurope.de/mirror/ftp.archlinux.org/core/os/x86_64 mirror (even not a https one!).
Can this be a result of improper mirror synchronization or some other problem with that mirror?

**Comment by pfactum** [comment]
> http://ftp.hosteurope.de/mirror/ftp.archlinux.org/core/os/x86_64 mirror

It's unavailable for me, btw. Maybe, this is **the** issue?

If so, another mirror should be considered. Please see [this mail](https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/GNYDIXOYB6JIB62KP5TDM7N3N2CZRIQD/) regarding using a geo mirror. And for Europe, there's https://europe.mirror.pkgbuild.com/.

**Comment by KottV** [comment]
Why it prints http here? `http //ftp.hosteurope.de/mirror/ftp.archlinux.org/core/os/x86_64/gnutls-3.7.5-2-x86_64.pkg.tar.zst  remote error  Not Found`
Or this is just a word and is not related to the passed URL?

**Comment by adrianschroeter** [comment]
not a build script bug ... and it seems to work on build.o.o as well
