### ISSUE TITLE
#!ArchExclusiveLine and #!ArchExcludedLine do not appear to get honored during the build

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-build#846]
The documentation (https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.supported_formats.html#id-1.5.10.8.5) mentions that `Dockerfile` based builds support the special instructions `#!ArchExclusiveLine` and `#!ArchExcludedLine` via:
https://github.com/openSUSE/obs-build/blob/dfe6687bfac0c2696123e442499f210a30b7054a/Build/Docker.pm#L273

I have tried this via the following `Dockerfile`:
```Dockerfile
#!ArchExclusiveLine: aarch64
ENV CC=/usr/bin/gcc-11
#!ArchExcludedLine: aarch64
ENV CC=/usr/bin/gcc-7
```
but this has no effect. `obs-build` executes both lines which leads to wrong results on aarch64 and works everywhere else only by accident.

**Comment by mlschroe** [comment]
That's because they are aimed at the Dockerfile parser. They were added as workaround that we cannot execute complex bash statements that test the architecture in the parser.
The Dockerfile itself is not changed and the docker/buildah commands just skip the comment.

**Comment by dcermak** [comment]
Would it be possible to exclude these lines from the actual build?

**Comment by mlschroe** [comment]
The goal is that you also should be able to build the container outside of the build service. So I don't think this is reasonable.

**Comment by dcermak** [comment]
Fair enough
