### ISSUE TITLE
Missing --recurse-submodules parameter for git cloning

### ISSUE THREAD

**Issue by mcepl** [openSUSE/obs-build#849]
https://github.com/openSUSE/obs-build/blob/e82ad7023a03a81e0d48f44f0260ced7b6c0643e/PBuild/RemoteAssets.pm#L295

See https://build.opensuse.org/package/show/home:mcepl:work/rofi-wayland Its source code is indicated in the SPEC file by line:

```spec
#!RemoteAssetUrl: git+https://github.com/lbonn/rofi.git
```

Unfortunately the build fails because submodules of the remote assets (in the `subprojects/` folder) are not updated. Adding `--recurse-submodules` parameter to `git clone` command here would probably help.

**Comment by jfehlig** [comment]
FYI, I opened this similar issue under the wrong project

https://github.com/openSUSE/open-build-service/issues/12909

Feel free to close it and go with this report.

**Comment by adrianschroeter** [comment]
I did this, but I am a bit unsure if that is actually your problem. Because this is for remote assets and not for scmsync repositories. If you need it there, we would need to do it in the scm bridge

**Comment by mcepl** [comment]
Yes, I need it for remote assets. I don’t think the scmsync repositories would be ever so complicated, that submodules would be an issue.

**Comment by jfehlig** [comment]
@adrianschroeter, is your change deployed to IBS? After a successful remote service run of `/home:jfehlig:gitlab-ci/libvirt`, the libvirt.obscpio archive does not contain the expanded keycodemapdb submodule in src/keycodemapdb/. Thanks!

**Comment by mcepl** [comment]
I think this will go to the `build` script which is part of the `build` package. However, I haven’t managed to build it in my project https://build.opensuse.org/package/show/home:mcepl:work/build

**Comment by jfehlig** [comment]
Maybe I misunderstand how this stuff works, but I don't see how an updated `build` package would help me. I make changes to a gitlab repo referenced by <scmsync> in an obs package, and then issue `osc service rr` on the package. No use of `build` in this scenario afaik.

**Comment by adrianschroeter** [comment]
JFYI, the build script including this change is deployed now (since a few minutes).

**Comment by jfehlig** [comment]
I issued a `osci service rr home:jfehlig:gitlab-ci/libvirt`, which created a new libvirt.obscpio, but it does not contain the expanded keycodemapdb submodule
https://build.suse.de/package/show/home:jfehlig:gitlab-ci/libvirt
