### ISSUE TITLE
Dockerfile fails to build if some containers in FROM don't have /bin/sh 

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/obs-build#873]
If a Dockerfile use some additional container for multi-stage build which don't have /bin/sh, build will fail since obs-build doesn't detect this kind of container as a "scratch" container and will try to add OBS support for it.

Minimal example available at https://build.opensuse.org/package/show/home:fcrozat:BCI/obs-build-fails-noshell

```
#!BuildTag: obs/noshell_fail:0.1

FROM crazymax/goreleaser-xx:1.2.5 AS goreleaser-xx

FROM registry.suse.com/bci/golang:1.18 AS base
COPY --from=goreleaser-xx / /
WORKDIR /src

FROM base as build
RUN goreleaser-xx --help 
```

**Comment by mlschroe** [comment]
This is now fixed. Thanks!
