### ISSUE TITLE
build-pkg-rpm: line 183: zstd: command not found

### ISSUE THREAD

**Issue by adrianreber** [openSUSE/obs-build#892]
I added to one of my packages the CentOS9 repositories in OBS and it only fails on x86_64 but builds on aarch64.

It also builds on Leap and CentOS8. Not sure why it fails on CentOS9 x86_64 with `build-pkg-rpm: line 183: zstd: command not found`.

https://obs.openhpc.community/package/live_build_log/home:adrianr/ohpc-filesystem/CentOS9/x86_64

This is probably my error when setting up the repository, but I am not sure how to solve it. Any recommendations on how to fix this?

**Comment by adrianschroeter** [comment]
you may want to check the config of Stream:9 of our instance, esp. the mock substitute. But please use normal support channels like irc or the mailing list instead of bug reporting tracking for your configuration issues in future.
