### ISSUE TITLE
changes file format does not allow a file header

### ISSUE THREAD

**Issue by pbrkr** [openSUSE/obs-build#902]
It's good practice to ensure that all files in a project include a header which identifies the author, copyright & licensing information. The changes file format used by OpenSUSE doesn't support such a header though.

A possible header format would be as follows, using `#` as a leading character to match the format of comments in a spec file:

```
# Copyright (c) 2020-2022 Paul Barker
# SPDX-License-Identifier: CC-BY-4.0
```

If I add this header to a changes file, both `vc` and `changelog2spec` don't handle it.

* `vc` adds new changelog entries at the top of the file, moving the header out of place.
* `changelog2spec` complains that the changelog format is unknown.

Is it possible to extend the changes file format to allow such a header?

**Comment by coolo** [comment]
changes files format doesn't have comments. It's a split out of the spec file and the spec file license applies. Put your license there.

**Comment by adrianschroeter** [comment]
usually we state that the license of all contributed content by a SUSE employee is always under the license of the upstream. This would include the changelog IMHO.

I am not sure that this applies also for all 3rd party contributions. However this is a topic for the opensuse project mailing list IMHO. We can look into this feature again when an agreement is achieved there.

**Comment by pbrkr** [comment]
@adrianschroeter: By "project mailing list" do you mean https://lists.opensuse.org/archives/list/project@lists.opensuse.org/? Looking at the recent archives that appears to be mostly administrative discussion. But I'm happy to raise the query there if that is the correct place.
