### ISSUE TITLE
build-pkg-rpm: chroot: failed to run command '<lua>': No such file or directory

### ISSUE THREAD

**Issue by wb0716** [openSUSE/obs-build#959]
I came to an issue during Preinstalling a package.
In the config file, there is such section: Runscripts: setup
In setup.spec file, there is such 
%post -p <lua>
   xxxx
So. During preinstalling the setup package, there will be such error:
running setup postinstall script
 chroot: failed to run command '<lua>': No such file or directory.
when calling command: rpm -qp --nodigest --nosignature --qf "%{POSTINPROG}" setup-0.5-1.1.noarch.rpm
it shows: <lua>
Please check this issue. Thanks.

**Comment by adrianschroeter** [comment]
this sounds more like a bug in the rpm scripts or dependency order problem.

However, without any reproducer I can only close this.
