### ISSUE TITLE
Feature: support conditional ExclusiveArch

### ISSUE THREAD

**Issue by vasiliy-ul** [openSUSE/obs-build#969]
The scheduler currently does not seem to evaluate conditionals:

https://github.com/openSUSE/obs-build/blob/b5debf616ee470fa2cf03371d272675c3714e308/Build/Rpm.pm#L790-L793

As a result, none of the following snippets work (i.e. the aarch64 build is always scheduled):

```spec
%if 0%{?is_opensuse}
ExclusiveArch:  x86_64 aarch64
%else
ExclusiveArch:  x86_64
%endif
```

```spec
%if 0%{?is_opensuse}
%define _exclusive_arches x86_64 aarch64
%else
%define _exclusive_arches x86_64
%endif
...
ExclusiveArch:  %{_exclusive_arches}
```

**Comment by mlschroe** [comment]
They are certainly evaluated. Can you please point me to a project in OBS where it doesn't seem to work?

**Comment by vasiliy-ul** [comment]
Ooops, seems I somehow messed up with the is_opensuse macro. Did one more checking and indeed, it works now. So my bad, and sorry for the noise. Closing the issue.
